### ISSUE TITLE
Create contributing file

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/our-site-v1-DEFUNCT#414]
so we need a guide to contributing, I think we can keep it super basic.

We should also have some maintainers..

**Comment by rebeccaradding** [comment]
@des-des agreed! @jsms90 we've talked about this quite a bit, do you have any thoughts here?

@sofer, how many maintainers would you suggest, and who should they be?

**Comment by iteles** [comment]
No longer relevant for this defunct repo.
